quarkus.package.main-class=demo.LsToolDemo

## GPULlama3 configuration
quarkus.langchain4j.gpu-llama3.enable-integration=true
quarkus.langchain4j.gpu-llama3.chat-model.model-name=unsloth/Llama-3.2-1B-Instruct-GGUF
quarkus.langchain4j.gpu-llama3.chat-model.quantization=Q8_0
#quarkus.langchain4j.gpu-llama3.chat-model.model-name=ggml-org/Qwen3-0.6B-GGUF
#quarkus.langchain4j.gpu-llama3.chat-model.quantization=f16
#for llama
quarkus.langchain4j.gpu-llama3.chat-model.temperature=0.3
quarkus.langchain4j.gpu-llama3.chat-model.top-p=0.95
#for qwen
#quarkus.langchain4j.gpu-llama3.chat-model.temperature=0.6
#quarkus.langchain4j.gpu-llama3.chat-model.top-p=0.95

quarkus.langchain4j.gpu-llama3.chat-model.max-tokens=2048

## Log requests/responses to see tool call round-trips in the output
quarkus.langchain4j.gpu-llama3.log-requests=true
quarkus.langchain4j.gpu-llama3.log-responses=true
