quarkus.package.main-class=demo.JavaCoderIterativeDemo

## GPULlama3 configuration
quarkus.langchain4j.gpu-llama3.enable-integration=true
quarkus.langchain4j.gpu-llama3.chat-model.model-name=unsloth/Llama-3.2-1B-Instruct-GGUF
quarkus.langchain4j.gpu-llama3.chat-model.quantization=F16
quarkus.langchain4j.gpu-llama3.chat-model.temperature=0.2
quarkus.langchain4j.gpu-llama3.chat-model.top-p=0.95
quarkus.langchain4j.gpu-llama3.chat-model.max-tokens=2048

quarkus.langchain4j.gpu-llama3.log-requests=true
quarkus.langchain4j.gpu-llama3.log-responses=true
